<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>Robust.Server</AssemblyName>
    <RootNamespace>Robust.Server</RootNamespace>
    <AssemblyVersion>283.1.0.0</AssemblyVersion>
    <FileVersion>283.1.0.0</FileVersion>
    <Version>283.1.0</Version>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\vendor\RobustToolbox\Robust.Shared\Robust.Shared.csproj" />
  </ItemGroup>
</Project>
