using System.Reflection.Metadata;
using System.Reflection.PortableExecutable;
using System.Text;
using System.Text.RegularExpressions;

var stubDll = args.ElementAtOrDefault(0)
              ?? Path.GetFullPath(Path.Combine(
                  AppContext.BaseDirectory, "..", "..", "..", "..", "..",
                  "src", "Port.RobustClientStub", "bin", "Debug", "net10.0", "Robust.Client.dll"));
var contentClient = args.ElementAtOrDefault(1)
                    ?? @"c:\ss14\space-station-14\bin\Content.Client\Content.Client.dll";
var outPath = args.ElementAtOrDefault(2)
              ?? Path.GetFullPath(Path.Combine(
                  AppContext.BaseDirectory, "..", "..", "..", "..", "..",
                  "src", "Port.RobustClientStub", "Generated", "TypeShells.g.cs"));

if (!File.Exists(stubDll))
{
    // Fall back to any built stub beside the probe.
    var alt = Path.GetFullPath(Path.Combine(
        AppContext.BaseDirectory, "..", "..", "..", "..", "..",
        "tools", "ProbeContentClientLoad", "bin", "Debug", "net10.0", "Robust.Client.dll"));
    if (File.Exists(alt)) stubDll = alt;
}

// Hand-written stubs only (exclude Generated/) so re-runs can fix shell shapes.
var existing = new HashSet<string>(StringComparer.Ordinal);
var stubRoot = Path.GetFullPath(Path.Combine(Path.GetDirectoryName(outPath)!, ".."));
foreach (var cs in Directory.EnumerateFiles(stubRoot, "*.cs", SearchOption.AllDirectories))
{
    if (cs.Contains($"{Path.DirectorySeparatorChar}Generated{Path.DirectorySeparatorChar}", StringComparison.OrdinalIgnoreCase)
        || cs.Contains("/Generated/", StringComparison.OrdinalIgnoreCase))
        continue;
    var text = File.ReadAllText(cs);
    var nsMatch = Regex.Match(text, @"^namespace\s+([\w.]+)", RegexOptions.Multiline);
    var ns = nsMatch.Success ? nsMatch.Groups[1].Value : "";
    foreach (Match m in Regex.Matches(
                 text,
                 @"^\s*public\s+(?:abstract\s+|sealed\s+|partial\s+)*(?:class|interface|enum|struct|record)\s+(\w+)",
                 RegexOptions.Multiline))
    {
        var name = m.Groups[1].Value;
        if (name.Length == 0) continue;
        var full = string.IsNullOrEmpty(ns) ? name : ns + "." + name;
        existing.Add(full);
        if (Regex.IsMatch(text, @"class\s+" + Regex.Escape(name) + @"\s*<"))
            existing.Add(full + "`1");
    }
}
_ = stubDll; // kept for CLI compatibility / future IL verification

var refs = new SortedSet<string>(StringComparer.Ordinal);
using (var fs = File.OpenRead(contentClient))
using (var pe = new PEReader(fs))
{
    var mr = pe.GetMetadataReader();
    foreach (var h in mr.TypeReferences)
    {
        var t = mr.GetTypeReference(h);
        var ns = mr.GetString(t.Namespace);
        var name = mr.GetString(t.Name);
        if (ns.StartsWith("Robust.Client", StringComparison.Ordinal))
            refs.Add(ns + "." + name);
    }
}

var missing = refs.Where(r => !HasType(existing, r)).ToList();
Directory.CreateDirectory(Path.GetDirectoryName(outPath)!);

var sb = new StringBuilder();
sb.AppendLine("// <auto-generated />");
sb.AppendLine("// Content.Client type-ref shells for Android host load. Not a Clyde implementation.");
sb.AppendLine("#nullable enable");
sb.AppendLine("using System;");
sb.AppendLine("using System.Collections.Generic;");
sb.AppendLine("using Robust.Shared.GameObjects;");
sb.AppendLine();

var byNs = missing.GroupBy(FullNs).OrderBy(g => g.Key, StringComparer.Ordinal);
foreach (var g in byNs)
{
    sb.Append("namespace ").Append(g.Key).AppendLine();
    sb.AppendLine("{");
    foreach (var full in g.OrderBy(x => x, StringComparer.Ordinal))
    {
        var simple = SimpleName(full);
        EmitType(sb, g.Key, simple, full);
        sb.AppendLine();
    }
    sb.AppendLine("}");
    sb.AppendLine();
}

File.WriteAllText(outPath, sb.ToString());
Console.WriteLine($"wrote {missing.Count} shells → {outPath}");

static bool HasType(HashSet<string> existing, string full)
{
    if (existing.Contains(full)) return true;
    // VisualizerSystem`1 vs VisualizerSystem`1 / VisualizerSystem
    var tick = full.IndexOf('`');
    if (tick > 0)
    {
        var bare = full[..tick];
        if (existing.Any(e => e == bare || e.StartsWith(bare + "`", StringComparison.Ordinal)))
            return true;
    }
    return existing.Any(e => e.StartsWith(full + "`", StringComparison.Ordinal));
}

static string FullNs(string full)
{
    var i = full.LastIndexOf('.');
    return i < 0 ? "" : full[..i];
}

static string SimpleName(string full)
{
    var i = full.LastIndexOf('.');
    return i < 0 ? full : full[(i + 1)..];
}

static void EmitType(StringBuilder sb, string ns, string simple, string full)
{
    // Handled in dedicated source files — skip duplicates for critical shells.
    if (full is "Robust.Client.GameObjects.VisualizerSystem`1"
        or "Robust.Client.GameObjects.AppearanceSystem"
        or "Robust.Client.GameObjects.AppearanceChangeEvent"
        or "Robust.Client.GameObjects.AnimationPlayerSystem"
        or "Robust.Client.GameObjects.AnimationPlayerComponent"
        or "Robust.Client.GameObjects.AnimationCompletedEvent"
        or "Robust.Client.GameObjects.SpriteSystem"
        or "Robust.Client.GameObjects.SpriteComponent"
        or "Robust.Client.UserInterface.CustomControls.DefaultWindow"
        or "Robust.Client.UserInterface.Controllers.UIController")
    {
        sb.AppendLine($"    // (hand-written) {simple}");
        return;
    }

    var (name, arity) = ParseArity(simple);

    if (name.EndsWith("Attribute", StringComparison.Ordinal))
    {
        EmitClass(sb, name, arity, ": Attribute", sealedClass: true);
        return;
    }

    // Interfaces before Controls — e.g. IViewportControl lives under CustomControls.
    if (name.StartsWith('I') && name.Length > 1 && char.IsUpper(name[1]))
    {
        EmitInterface(sb, name, arity);
        return;
    }

    if (full.Contains(".Controls.", StringComparison.Ordinal)
        || full.Contains(".CustomControls.", StringComparison.Ordinal))
    {
        var baseType = GuessControlBase(ns, name);
        EmitClass(sb, name, arity, baseType is null ? "" : ": " + baseType);
        return;
    }

    if (name.EndsWith("Delegate", StringComparison.Ordinal) || full.Contains("CopyPixelsDelegate", StringComparison.Ordinal))
    {
        EmitDelegate(sb, name, arity);
        return;
    }

    if (LooksLikeEnum(name))
    {
        sb.Append("    public enum ").Append(name).AppendLine(" : byte");
        sb.AppendLine("    {");
        sb.AppendLine("        None = 0,");
        sb.AppendLine("    }");
        return;
    }

    if (name.EndsWith("Event", StringComparison.Ordinal)
        || name.EndsWith("EventArgs", StringComparison.Ordinal))
    {
        EmitClass(sb, name, arity, name.EndsWith("EventArgs", StringComparison.Ordinal) ? ": EventArgs" : "");
        return;
    }

    if (name.EndsWith("Component", StringComparison.Ordinal))
    {
        EmitClass(sb, name, arity, ": global::Robust.Shared.GameObjects.Component");
        return;
    }

    if (name.EndsWith("System", StringComparison.Ordinal)
        && (ns.Contains("GameObjects", StringComparison.Ordinal)
            || ns.Contains("Audio", StringComparison.Ordinal)
            || ns.Contains("Physics", StringComparison.Ordinal)
            || ns.Contains("Debugging", StringComparison.Ordinal)
            || ns.Contains("ComponentTrees", StringComparison.Ordinal)))
    {
        EmitClass(sb, name, arity, ": global::Robust.Shared.GameObjects.EntitySystem");
        return;
    }

    if (name is "Overlay")
    {
        // Already defined in hand-written Graphics/Overlay stubs.
        sb.AppendLine("    // (hand-written) Overlay");
        return;
    }

    if (name is "GridOverlay")
    {
        EmitClass(sb, name, arity, ": global::Robust.Client.Graphics.Overlay");
        return;
    }

    if (name is "State")
    {
        sb.AppendLine("    // (hand-written) State");
        return;
    }

    if (name is "UIScreen")
    {
        EmitClass(sb, name, arity, ": global::Robust.Client.UserInterface.Control");
        return;
    }

    if (name is "ClientRunLevel")
    {
        sb.AppendLine("    // (hand-written) ClientRunLevel");
        return;
    }

    if (name is "PlacementMode" or "PlacementHijack")
    {
        EmitClass(sb, name, arity, "", abstractClass: true);
        return;
    }

    if (name is "BaseReplayCommand" or "LoadReplayJob" or "AnimationTrackProperty")
    {
        EmitClass(sb, name, arity, "", abstractClass: true);
        return;
    }

    EmitClass(sb, name, arity, "");
}

static string? GuessControlBase(string ns, string name) => name switch
{
    "DefaultWindow" => "global::Robust.Client.UserInterface.CustomControls.BaseWindow",
    "ContainerButton" => "global::Robust.Client.UserInterface.Controls.Button",
    "BaseButton" => "global::Robust.Client.UserInterface.Control",
    "CheckBox" or "CheckButton" => "global::Robust.Client.UserInterface.Controls.Button",
    "TextureRect" or "AnimatedTextureRect" or "LayeredTextureRect" => "global::Robust.Client.UserInterface.Control",
    "UIWidget" => "global::Robust.Client.UserInterface.Control",
    "Popup" or "PopupContainer" => "global::Robust.Client.UserInterface.Control",
    "GridContainer" => "global::Robust.Client.UserInterface.Controls.Container",
    "ProgressBar" or "Slider" or "Range" or "SpinBox" or "FloatSpinBox" => "global::Robust.Client.UserInterface.Control",
    "TabContainer" or "VerticalTabContainer" or "SplitContainer" => "global::Robust.Client.UserInterface.Controls.Container",
    "ItemList" or "Tree" or "OutputPanel" or "TextEdit" or "HistoryLineEdit" => "global::Robust.Client.UserInterface.Control",
    "OptionButton" or "MultiselectOptionButton" => "global::Robust.Client.UserInterface.Control",
    "SpriteView" or "EntityPrototypeView" => "global::Robust.Client.UserInterface.Control",
    "UIRoot" or "WindowRoot" => "global::Robust.Client.UserInterface.Control",
    "CenterContainer" or "Collapsible" or "CollapsibleBody" or "CollapsibleHeading" =>
        "global::Robust.Client.UserInterface.Controls.Container",
    "HScrollBar" or "VScrollBar" or "ScrollBar" => "global::Robust.Client.UserInterface.Control",
    "ColorableSlider" or "ColorSelectorSliders" or "SliderIntInput" => "global::Robust.Client.UserInterface.Control",
    "RadioOptions" => "global::Robust.Client.UserInterface.Control",
    "Tooltip" or "FpsCounter" or "EntitySpawnWindow" or "ViewportContainer" or "PrototypeListContainer" =>
        "global::Robust.Client.UserInterface.Control",
    _ => ns.Contains("Controls", StringComparison.Ordinal) && name is not "Control"
        ? "global::Robust.Client.UserInterface.Control"
        : null,
};

static bool LooksLikeEnum(string name) =>
    name is "MidiRendererStatus" or "PhysicsDebugFlags" or "AccessLevel" or "DebugMonitor"
        or "KeyBindingType" or "KeyEventType" or "ScreenshotType" or "DrawPrimitiveTopology"
        or "RenderTargetColorFormat" or "RadioOptionsLayout" or "ClientRunLevel";

static (string Name, int Arity) ParseArity(string simple)
{
    var tick = simple.IndexOf('`');
    if (tick < 0) return (simple, 0);
    return (simple[..tick], int.Parse(simple[(tick + 1)..]));
}

static string TypeParams(int arity)
{
    if (arity <= 0) return "";
    return "<" + string.Join(", ", Enumerable.Range(1, arity).Select(i => "T" + (arity == 1 ? "" : i.ToString()))) + ">";
}

static void EmitClass(StringBuilder sb, string name, int arity, string bases,
    bool abstractClass = false, bool sealedClass = false)
{
    var mods = abstractClass ? "abstract " : sealedClass ? "sealed " : "";
    sb.Append("    public ").Append(mods).Append("class ").Append(name).Append(TypeParams(arity));
    if (!string.IsNullOrEmpty(bases)) sb.Append(' ').Append(bases);
    sb.AppendLine();
    sb.AppendLine("    {");
    sb.AppendLine("    }");
}

static void EmitInterface(StringBuilder sb, string name, int arity)
{
    sb.Append("    public interface ").Append(name).Append(TypeParams(arity)).AppendLine();
    sb.AppendLine("    {");
    sb.AppendLine("    }");
}

static void EmitDelegate(StringBuilder sb, string name, int arity)
{
    sb.Append("    public delegate void ").Append(name).Append(TypeParams(arity))
        .AppendLine("(object? sender, EventArgs e);");
}
